name: CI

on:
  push:
    branches-ignore:
      - 'generated'
      - 'codegen/**'
      - 'integrated/**'
      - 'stl-preview-head/**'
      - 'stl-preview-base/**'
  pull_request:
    branches-ignore:
      - 'stl-preview-head/**'
      - 'stl-preview-base/**'

jobs:
  lint:
    name: lint
    timeout-minutes: 10
    runs-on: ${{ github.repository == 'stainless-sdks/jocall3-python' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.9.13'

      - name: Install Python lint tools
        run: |
          python -m pip install --upgrade pip
          pip install isort ruff httpx

      - name: Run lints
        run: ./scripts/lint

  build:
    name: build
    timeout-minutes: 10
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    permissions:
      contents: read
      id-token: write
    runs-on: ${{ github.repository == 'stainless-sdks/jocall3-python' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.9.13'

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run build
        run: uv build

      - name: Get GitHub OIDC Token
        if: github.repository == 'stainless-sdks/jocall3-python'
        id: github-oidc
        uses: actions/github-script@v8
        with:
          script: core.setOutput('github_token', await core.getIDToken());

      - name: Upload tarball
        if: github.repository == 'stainless-sdks/jocall3-python'
        env:
          URL: https://pkg.stainless.com/s
          AUTH: ${{ steps.github-oidc.outputs.github_token }}
          SHA: ${{ github.sha }}
        run: ./scripts/utils/upload-artifact.sh

  test:
    name: test
    timeout-minutes: 10
    runs-on: ${{ github.repository == 'stainless-sdks/jocall3-python' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.9.13'

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Install Python test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx pytest pytest-asyncio respx anyio

      - name: Run tests
        run: pytest -n 1 --maxfail=1 --disable-warnings
